// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGWALCbccOMtV8IPBtYppmEQhFQxwyjDI',
    appId: '1:513488495547:web:7d2baa2b4b13725cbb9a9e',
    messagingSenderId: '513488495547',
    projectId: 'studysync-73a0f',
    authDomain: 'studysync-73a0f.firebaseapp.com',
    databaseURL: 'https://studysync-73a0f-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'studysync-73a0f.firebasestorage.app',
    measurementId: 'G-EJ4YH9MH9Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClK4GM_GzKlWO5yyAs451EDIfXAPK-GNg',
    appId: '1:513488495547:android:104cfadb0023db57bb9a9e',
    messagingSenderId: '513488495547',
    projectId: 'studysync-73a0f',
    databaseURL: 'https://studysync-73a0f-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'studysync-73a0f.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYUAshLS3Uf53m_WU0ogz-V5OyOVf_Z3M',
    appId: '1:513488495547:ios:a2eef7ad9302d836bb9a9e',
    messagingSenderId: '513488495547',
    projectId: 'studysync-73a0f',
    databaseURL: 'https://studysync-73a0f-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'studysync-73a0f.firebasestorage.app',
    androidClientId: '513488495547-kmho7qfeqh1l6c20rnmh1ktdg7icn14g.apps.googleusercontent.com',
    iosClientId: '513488495547-qvn5nc5p9he2bcfairhl7ipn3492h6ik.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAYUAshLS3Uf53m_WU0ogz-V5OyOVf_Z3M',
    appId: '1:513488495547:ios:a2eef7ad9302d836bb9a9e',
    messagingSenderId: '513488495547',
    projectId: 'studysync-73a0f',
    databaseURL: 'https://studysync-73a0f-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'studysync-73a0f.firebasestorage.app',
    androidClientId: '513488495547-kmho7qfeqh1l6c20rnmh1ktdg7icn14g.apps.googleusercontent.com',
    iosClientId: '513488495547-qvn5nc5p9he2bcfairhl7ipn3492h6ik.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDGWALCbccOMtV8IPBtYppmEQhFQxwyjDI',
    appId: '1:513488495547:web:fd4cea1a597ad6d8bb9a9e',
    messagingSenderId: '513488495547',
    projectId: 'studysync-73a0f',
    authDomain: 'studysync-73a0f.firebaseapp.com',
    databaseURL: 'https://studysync-73a0f-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'studysync-73a0f.firebasestorage.app',
    measurementId: 'G-VW2VNSHTK2',
  );
}
